### ISSUE TITLE
Feedback!

### ISSUE THREAD

**Issue by vkinnealey** [jaclynglover/finalproject#1]
Great idea! A smart site to have and I think it will serve a very cool purpose. My only comment would be finding a way to get your meta box showing your run details public (which is sounds like you were already trying to do) as it would be convenient to have that information available on the live site as opposed to just on the back end. Great job!

**Comment by jaclynglover** [comment]
Thanks, Victoria! I played around with trying to get my metabox details to show up on my post, but I didn't like how it looked on the page. For now, I'm just going to save the box details for my reference, but hopefully I can get it working and looking nice sometime soon.

Thanks again for your feedback!
