### ISSUE TITLE
A Couple of Notes

### ISSUE THREAD

**Issue by xof88** [jaclynglover/finalproject#10]
Hi Jaclyn! Really great work on your site!  As a fellow runner I can appreciate how great it is to track routes and progress, and how every run I basically spend the whole time thinking/writing a blog in my head - what a perfect outlet on the site! I don't have much feedback for you, sorry, but here are a couple notes for you to take or leave as you wish:)

1. Since your header and the posts have white backgrounds, perhaps add a background color to both rails on the Home page. That pretty pink from the menu?
2. Explore other running blogs out there and see if any other plugins or ideas come to you to fill this out some more. I used to follow a ton and some people have some really creative ideas or add-ons. 

Best of luck with your upcoming races!
Jane

**Comment by jaclynglover** [comment]
Thanks! I've been reading through some other blogs to see how I can build out my site more. I'll probably be adding some plugins soon!
