### ISSUE TITLE
The Meta Box Struggle Is Real 

### ISSUE THREAD

**Issue by tatyanaberdan** [jaclynglover/finalproject#11]
Awesome job on your site and congrats on getting so far in your customizations! 

I have to super minor notes because honestly I think your site looks great:

-I noticed when you hover over the twitter and facebook icons in your sidebar, you get a couple of buttons that say "follow us" or "visit us" rather than "follow me" and "visit me" and when you hover over the email and instagram icons, nothing pops up - you might consider making the buttons consistent, if it looks like an easy fix?   
-I would suggest getting rid of the 'uncategorized' category in your posts or renaming it something a bit more specific so people know what types of posts they might find if they choose to explore this category

Best of luck in wrangling those meta boxes this weekend. I'm rooting for us!

**Comment by jaclynglover** [comment]
Thank you for your feedback!

As suggested, I changed the "uncategorized" category to be called "Random Thoughts." It's kind of a catch-all for all the posts that don't fall under my other two categories.
