### ISSUE TITLE
Feedback!

### ISSUE THREAD

**Issue by mollykorroch** [jaclynglover/finalproject#12]
Ok, first, I truly admire you for running! My favorite part of the blog is definitely the custom post--you obviously worked really really hard on this and it's paid off. Really well done. Not clunky at all—it’s designed quite nicely. And you wrote your own plug in!! So cool. (You won't be the only one to follow it! I hope you post your updates on social media.)

**Comment by jaclynglover** [comment]
Thank you for your nice comments! I'm looking forward to adding more content to my site and refining my custom post type plugin. 

Thanks again!
