### ISSUE TITLE
Custom Post Plugin

### ISSUE THREAD

**Issue by amaliaks** [jaclynglover/finalproject#5]
Jaclyn, your site is the best! I'm inspired to do more to my site via code after working with you on your code (mostly you helping me) and with the end product that you were able to get. My suggestion is to keep your custom meta box information on the page and find a way to update the font and color of that information. I think that information would be useful to someone reading your posts and encourage others to run. Not to mention, that information could help show you how you're getting faster! Just something to consider later on if you could manipulate the CSS.

**Comment by jaclynglover** [comment]
Thanks, girl! I tried to get the metabox details to show on my posts, but wasn't liking how it looked. I'm going to have to play around with it more, and hopefully I'll get it working and looking good sometime soon.

Thanks for being such a great support throughout this project and class! We did it!
