### ISSUE TITLE
search bar moving to bottom of page

### ISSUE THREAD

**Issue by vkinnealey** [jaclynglover/finalproject#6]
One other thought -- when the screen is narrow, your search bar jumps down to the bottom of the page, below the comments section .May be difficult to fix, but its a bit confusing to have it at the bottom/easy to miss - if possible it would be great if it was static on the side no matter the page width!

**Comment by jaclynglover** [comment]
Thank you for pointing this out. Unfortunately, I can't figure out how to change this without being afraid that I'm going to mess my site up, since it's part of my parent theme functionality. I hope to figure it out in the future!
